version: "2"

services:
  psaenz_gudtech_interview: 
    build: .
    ports: 
      - 3000:80
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/psaenz_gudtech_db
      - PORT=80
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psaenz_gudtech_db
